### ISSUE TITLE
Add `setup.py version` to docs

### ISSUE THREAD

**Issue by dee909** [python-versioneer/python-versioneer#204]
It would be awesome to have the `versioneer` command line support a sub command to show the current version:
```
$ versioneer show
2.5.0
```
or even better, a default behavior when install is already done:
```
$ versioneer
Usage: versioneer install

$ versioneer install
...

$ versioneer
1.0.0
```

It would run this line I end up writing a lot of times:
`python -c "import versioneer; print(versioneer.get_version())"`

(I might be missing something though, since this sounds like a very commun case.)

**Comment by exarkun** [comment]
A lot of version information is available to any project using versioneer already:

```
$ python setup.py version
running version
keywords are unexpanded, not using
got version from VCS {'error': None, 'date': '2020-02-27T10:28:13-0500', 'version': '0+untagged.429.g739a148', 'dirty': False, 'full-revisionid': '739a148ce320f0f5e6b50eeac40d7b19b0880a12'}
Version: 0+untagged.429.g739a148
 full-revisionid: 739a148ce320f0f5e6b50eeac40d7b19b0880a12
 dirty: False
 date: 2020-02-27T10:28:13-0500
```

I'm not sure if this ticket is a request for a command that *only* prints out the `version` item in that version dictionary without the extra noise or if this command satisfies the use-case.  The latter seems likely to me since this command does show the version as well as a bunch of other useful information that went into computing that version.

**Comment by dee909** [comment]
This command totally satisfies the use case, thanks !

Maybe mention it in the doc ?
I didn't know about this commad even though I had the impression I read the
doc carefully...

Thanks again :)
