### ISSUE TITLE
issue with get_cmdclass

### ISSUE THREAD

**Issue by jeeva-srinivasan** [python-versioneer/python-versioneer#233]
facing this issue - " AttributeError: module 'versioneer' has no attribute 'get_cmdclass' "
even after using the 0.19 version

**Comment by effigies** [comment]
If you're seeing that error, you probably have not [installed](https://github.com/python-versioneer/python-versioneer/blob/master/INSTALL.md) versioneer into the project.

Have you run `versioneer install` before running setup.py?

**Comment by jeeva-srinivasan** [comment]
yes I did a pip install versioneer

**Comment by effigies** [comment]
But not versioneer install? Please see the linked documentation.

**Comment by jeeva-srinivasan** [comment]
i'll try this

**Comment by effigies** [comment]
Please reopen if this is still an issue.

**Comment by zerothi** [comment]
Ok, this problem also arises in the following (I agree) bit weird situation:
- has `versioneer` system-wide
- patches the `setup.py` according to #193 
- running `pip` in a `no-build-isolation` mode.

The fix is quite easy (see my comment here: https://github.com/python-versioneer/python-versioneer/issues/193#issuecomment-958706634)

This should be the guideline for using versioneer I think.
