### ISSUE TITLE
Pip install complains of missing setup.cfg in a project based on pyproject.toml and setup.py

### ISSUE THREAD

**Issue by nabriis** [python-versioneer/python-versioneer#338]
I have a project which used config based on pyproject.toml and a setup.py files. I get the following error trying to install locally with `pip install .` I renamed my package name to `package`.

```
          exec(code, locals())
        File "<string>", line 5, in <module>
        File "<string>", line 1791, in get_version
        File "<string>", line 1723, in get_versions
        File "<string>", line 385, in get_config_from_root
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\username\\Desktop\\package\\setup.cfg'
```

I did run versioneer install and have a `_version.py` file which correctly handles my package `__version__`. Currently we have no tags.

Setup.py looks like this:

``` Python
from setuptools import setup
import versioneer

setup(
    version=versioneer.get_version(),
    cmdclass=versioneer.get_cmdclass()
)
```

and pyproject.toml (relevant parts only)
```
[build-system]
requires = ["setuptools>=42", "wheel", "versioneer==0.26"]
...
[project]
dynamic = ["dependencies", "version"]
...
[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "package/_version.py"
versionfile_build = "package/_version.py"
tag_prefix = ""
parentdir_prefix = "package-"
```

**Comment by effigies** [comment]
Try `"versioneer[toml]==0.26"`. It's not a required dependency, so it falls back to looking for `setup.cfg`.

**Comment by nabriis** [comment]
> Try `"versioneer[toml]==0.26"`. It's not a required dependency, so it falls back to looking for `setup.cfg`.

Thanks for the quick answer that seem to have worked! I would suggest updating the readme to specify this is needed for the pyproject.toml file👍

**Comment by effigies** [comment]
Good point! I thought I had...

**Comment by effigies** [comment]
Included in latest docs.

**Comment by jGaboardi** [comment]
I am trying to get a workflow set up for [updating `versioneer` automatically](https://github.com/pysal/spaghetti/pull/697) and I already have one set up for [creating a pypi release](https://github.com/pysal/spaghetti/blob/main/.github/workflows/release_and_publish.yml). This worked prior to [migrating to `pyproject.toml`](https://github.com/pysal/spaghetti/pull/690), but it is now failing since there is no `setup.cfg` in the repo. I *thought* I was following the guidelines here (and in the README), but [it looks like `versioneer` is still looking for a `setup.cfg`](https://github.com/jGaboardi/spaghetti/actions/runs/3906042098/jobs/6673764449#step:4:37). 

I'm 99.99% sure it's user error, as it always is, but I'm wondering if it would be possible to get a set of eyes of this?

cc @martinfleis

**Comment by effigies** [comment]
The environment versioneer is installed in needs to be Python 3.11+ or have `tomli` installed. You could change the `pip install versioneer` to `pip install versioneer[toml]`, and I suspect that would do the trick.

**Comment by jGaboardi** [comment]
@effigies Super! Your suggestion [worked](https://github.com/jGaboardi/spaghetti/actions/runs/3907438342/jobs/6676655566)! Double karma points for you today. Also, thanks a bundle for all your awesome work on `versioneer`, etc.
