### ISSUE TITLE
MANIFEST.in lines are sometimes (often?  usually?) redundant

### ISSUE THREAD

**Issue by exarkun** [python-versioneer/python-versioneer#40]
in my `setup.py` file I already do this:

```
setup(
    ...
    packages=["mypackage", ...],
)
```

This automatically includes all of the modules in `mypackage`.  It seems likely that most `setup.py` files are written like this or using the `setuptools` equivalent (`find_modules` or something) - though I see how it's not _necessarily_ the case that they are.

`versioneer-install` adds `mypackage/_version.py` to `MANIFEST.in` anyway.  This seems to be harmless but it is redundant and a distraction at best.  At worst it makes things confusing for someone trying to change how the package works (since they must now edit two things in order to change whether/how `_version.py` gets packaged).

It would be pretty cool not to add this file to `MANIFEST.in` if it is redundant to do so.

**Comment by FlorianWilhelm** [comment]
It would also be possible to get completely rid of `MANIFEST.in`. Check out https://docs.python.org/2/distutils/sourcedist.html#manifest and https://docs.python.org/2/distutils/setupscript.html#installing-additional-files. I implemented these techniques in PyScaffold (https://github.com/blue-yonder/pyscaffold/) and it works perfectly. That means for binary and source distribution there has been since Python 2.7 a single way to define additional data packages.

**Comment by warner** [comment]
I'm cool with not adding `_version.py` to MANIFEST.in. Are there any other redundancies you're seeing in there (in the current version)?

**Comment by anntzer** [comment]
I agree that `_version.py` does not need to be added to MANIFEST.  The other file added is `versioneer.py`, which is indeed not added by default.  However, versioneer already subclasses sdist, so it is easy to also add itself to the sdist at that point, simply by patching the `sdist.add_defaults` method.

If it does so, then versioneer won't need to play with MANIFEST.in at all anymore, which is probably a win for simplicity...
